#!/bin/bash

VERSION=0.1
CONFIG=/etc/kvm-backup.conf

function usage {
        echo "Usage: $(basename "$0") [-t|-c|-h|-v] -n" 2>&1
        echo '   -n    virtual machine name'
        echo '   -t    time in seconds to wait virtual machine shutdown'
        echo '   -c    configuration file path'
        echo '   -h    shows this help and exit'
        echo '   -v    shows version and exit'
        exit 1
}

if [[ ${#} -eq 0 ]]; then
   usage
fi

# Define list of arguments expected in the input
optstring=":n:t:c:hv"

while getopts ${optstring} arg; do
  case "${arg}" in
    n) vms+=("${OPTARG}") ;;
    t) TIME_SHUTDOWN=${OPTARG} ;;
    c) CONFIG=${OPTARG} ;;
    h) usage ;;
    v) echo "Version: ${VERSION}"
       exit 0 
       ;;
    \?)
      echo "Invalid option: -${OPTARG}."
      echo
      usage
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

if [ ! -f "${CONFIG}" ];
then
  echo "Configuration file doesn't exits"
  logger --tag "$(basename "$0")" --priority "local3.err" "Configuration file doesn't exits ${CONFIG}"
  exit 2
fi
logger --tag "$(basename "$0")" --priority "local3.info" "Loading configuration file ${CONFIG}"
# shellcheck source=/dev/null
source "${CONFIG}"

for vm in "${vms[@]}"; do
  echo "${vm}"
done
echo "${TIME_SHUTDOWN}"
echo "${SSHUSER}"